---
node_exporter_version: "1.6.1"
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
node_exporter_bin_dir: "/usr/local/bin"

node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_system_user: true
node_exporter_system_group: true

node_exporter_service_name: "node_exporter"
node_exporter_service_enabled: true

node_exporter_web_listen_address: "0.0.0.0:9100"

prometheus_config_dir: "/etc/prometheus"
prometheus_service_name: "prometheus"
prometheus_server: "localhost"
prometheus_target_host: "{{ ansible_host }}"
prometheus_target_port: "9100"