---
- name: Убедиться что стоят нужные пакеты
  package:
    name:
      - wget
      - tar
    state: present

- name: Создание группы Prometheus
  group:
    name: "{{ prometheus_group }}"
    system: "{{ prometheus_system_group }}"
    state: present

- name: Создание пользователя Prometheus
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    shell: /sbin/nologin
    system: "{{ prometheus_system_user }}"
    createhome: false
    home: "{{ prometheus_data_dir }}"

- name: Создание необходимых директорий
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Проверка установлен ли Prometheus
  stat:
    path: "{{ prometheus_bin_dir }}/prometheus"
  register: prometheus_binary

- name: Загрузка Prometheus
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
  when: not prometheus_binary.stat.exists

- name: Распаковка Prometheus
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
    dest: "/tmp"
    remote_src: yes
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64"
  when: not prometheus_binary.stat.exists

- name: Коппирование бинарников Prometheus
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_bin_dir }}/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
    remote_src: yes
  with_items:
    - prometheus
    - promtool
  when: not prometheus_binary.stat.exists

- name: Копирование консольных шаблонов Prometheus
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_config_dir }}/"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0755
    remote_src: yes
  with_items:
    - consoles
    - console_libraries
  when: not prometheus_binary.stat.exists

- name: Коппирование конфига Prometheus
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0644
  notify: reload prometheus

- name: Копирование Prometheus systemd service файла
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/{{ prometheus_service_name }}.service
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus

- name: Запуск и включение Prometheus
  systemd:
    name: "{{ prometheus_service_name }}"
    state: started
    enabled: "{{ prometheus_service_enabled }}"
    daemon_reload: true
