---
- name: Добавление FluentBit YUM репозитория
  yum_repository:
    name: fluentbit
    description: FluentBit repository
    baseurl: https://packages.fluentbit.io/centos/$releasever/
    gpgcheck: 1
    gpgkey: https://packages.fluentbit.io/fluentbit.key
    enabled: 1

- name: Установка FluentBit
  package:
    name: fluent-bit
    state: present
  failed_when: false

- name: Создание директорий FluentBit
  file:
    path: "{{ fluentbit_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Копирование конфига FluentBit
  template:
    src: fluent-bit.conf.j2
    dest: "{{ fluentbit_config_dir }}/fluent-bit.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart fluentbit

- name: Запуск и включение FluentBit 
  systemd:
    name: "{{ fluentbit_service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes
